worlds:
  FactionHub:
    min_x: -500
    max_x: 500
    min_z: -500
    max_z: 500
    msg: true
    msg_: "You have reached the limit!"
  Hub:
    min_x: -300
    max_x: 300
    min_z: -300
    max_z: 300
    msg: true
    msg_: "You have reached the limit in Hub!"
